# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_treasure_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
