# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_treasure_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(max_length=255),
        ),
    ]
